### ISSUE TITLE
Docs broken include of SSH-Private-Key-File-not-required.mdx fails

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer-plugin-googlecompute#134]
Example:

![image](https://user-images.githubusercontent.com/557699/205984169-93b52ff2-750a-4dd2-a340-a9ed903188fa.png)

From [Google Compute Builder](https://developer.hashicorp.com/packer/plugins/builders/googlecompute#ssh_local_tunnels)

**Comment by nywilken** [comment]
Thanks for catching this @rickard-von-essen. I opened a PR to fix up the docs.
